# Generated by Django 6.0.2 on 2026-02-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('laptop', 'Laptop'), ('monitor', 'Monitor'), ('servidor', 'Servidor')], max_length=20)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('en_reparacion', 'En reparacion'), ('dado_de_baja', 'Dado de baja')], default='operativo', max_length=20)),
            ],
        ),
    ]
