# Generated by Django 6.0.2 on 2026-02-22 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_initial'),
        ('soporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariomodel',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='inventario.equipomodel'),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentariomodel',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='soporte.ticketmodel'),
        ),
    ]
